version: "3"
services:
  db_resolver:
    image: golang:1.14
    tty: true
    command: bash
    working_dir: /go/src/github.com/oshiro3/db_resolver
    environment:
      TZ: Asia/Tokyo
      DB_RESOLVER_ROOT: /go/src/github.com/oshiro3/db_resolver
    volumes:
      - ./:/go/src/github.com/oshiro3/db_resolver

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db:/db

  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8081:80
  
  git_host:
    container_name: githost
    image: gitbucket/gitbucket
    volumes:
      - git_data:/gitbucket
    ports:
      - 8080:8080

volumes:
  git_data:  

